on:
  push:
    branches: ["feature/hw2-Maven"]
  pull_request:
    branches: ["feature/hw2-Maven"]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Package with Maven
        run: mvn package
