name: Date-time display

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  datetime:
    runs-on: ubuntu-latest
    steps:
      - name: Display date and time
      - run: date
